/**
 * Combination of grid widths of all kind of span numbers that generated by `CSSWidthgenerator`.
 *
 * @param prefix breakpoint name: sm | xm | lg
 */
export declare const CSSWidthSetGenerator: (prefix: 'sm' | 'xm' | 'lg') => import("styled-components").FlattenSimpleInterpolation[];
/**
 * Generate pre-defined CSS classes for `flex-direction`.
 *
 * `flex-direction: 'row' | 'row-reverse' | 'column' | 'column-reverse'`
 */
export declare const CSSDirectionGenerator: () => import("styled-components").FlattenSimpleInterpolation[];
/**
 * Generate pre-defined CSS classes for `justify-content`.
 *
 * `justify-content: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around'`
 */
export declare const CSSJustifyGenerator: () => import("styled-components").FlattenSimpleInterpolation[];
/**
 * Generate pre-defined CSS classes for `align-items`.
 *
 * `align-items: 'flex-start' | 'center' | 'flex-end' | 'baseline' | 'stretch'`
 */
export declare const CSSAlignItemsGenerator: () => import("styled-components").FlattenSimpleInterpolation[];
